// Code generated by MockGen. DO NOT EDIT.
// Source: ./../../../usecase/interfaces/update_project.go
//
// Generated by this command:
//
//	mockgen -source=./../../../usecase/interfaces/update_project.go -destination=./mocks/mock_update_project.go -package=resthandlmocks
//

// Package resthandlmocks is a generated GoMock package.
package resthandlmocks

import (
	context "context"
	updatemodel "projectservice/internal/usecase/models/updateproject"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUpdateProjectUsecase is a mock of UpdateProjectUsecase interface.
type MockUpdateProjectUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateProjectUsecaseMockRecorder
	isgomock struct{}
}

// MockUpdateProjectUsecaseMockRecorder is the mock recorder for MockUpdateProjectUsecase.
type MockUpdateProjectUsecaseMockRecorder struct {
	mock *MockUpdateProjectUsecase
}

// NewMockUpdateProjectUsecase creates a new mock instance.
func NewMockUpdateProjectUsecase(ctrl *gomock.Controller) *MockUpdateProjectUsecase {
	mock := &MockUpdateProjectUsecase{ctrl: ctrl}
	mock.recorder = &MockUpdateProjectUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateProjectUsecase) EXPECT() *MockUpdateProjectUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockUpdateProjectUsecase) Execute(ctx context.Context, in *updatemodel.UpdateProjectInput) (*updatemodel.UpdateProjectOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, in)
	ret0, _ := ret[0].(*updatemodel.UpdateProjectOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockUpdateProjectUsecaseMockRecorder) Execute(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockUpdateProjectUsecase)(nil).Execute), ctx, in)
}
