// Code generated by MockGen. DO NOT EDIT.
// Source: ./../../../repository/projectrepository/project_repository.go
//
// Generated by this command:
//
//	mockgen -source=./../../../repository/projectrepository/project_repository.go -destination=./mocks/mock_project_repository.go -package=middlewaremocks
//

// Package middlewaremocks is a generated GoMock package.
package middlewaremocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProjectRepository is a mock of ProjectRepository interface.
type MockProjectRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProjectRepositoryMockRecorder
	isgomock struct{}
}

// MockProjectRepositoryMockRecorder is the mock recorder for MockProjectRepository.
type MockProjectRepositoryMockRecorder struct {
	mock *MockProjectRepository
}

// NewMockProjectRepository creates a new mock instance.
func NewMockProjectRepository(ctrl *gomock.Controller) *MockProjectRepository {
	mock := &MockProjectRepository{ctrl: ctrl}
	mock.recorder = &MockProjectRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectRepository) EXPECT() *MockProjectRepositoryMockRecorder {
	return m.recorder
}

// GetOwnerId mocks base method.
func (m *MockProjectRepository) GetOwnerId(ctx context.Context, projectId uint32) (uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOwnerId", ctx, projectId)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOwnerId indicates an expected call of GetOwnerId.
func (mr *MockProjectRepositoryMockRecorder) GetOwnerId(ctx, projectId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOwnerId", reflect.TypeOf((*MockProjectRepository)(nil).GetOwnerId), ctx, projectId)
}
