// Code generated by MockGen. DO NOT EDIT.
// Source: ./../../../usecase/interfaces/login.go
//
// Generated by this command:
//
//	mockgen -source=./../../../usecase/interfaces/login.go -destination=mocks/mock_login.go -package=handlmocks
//

// Package handlmocks is a generated GoMock package.
package handlmocks

import (
	context "context"
	reflect "reflect"
	logmodel "userservice/internal/usecase/models/login"

	gomock "go.uber.org/mock/gomock"
)

// MockLoginUserUsecase is a mock of LoginUserUsecase interface.
type MockLoginUserUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockLoginUserUsecaseMockRecorder
	isgomock struct{}
}

// MockLoginUserUsecaseMockRecorder is the mock recorder for MockLoginUserUsecase.
type MockLoginUserUsecaseMockRecorder struct {
	mock *MockLoginUserUsecase
}

// NewMockLoginUserUsecase creates a new mock instance.
func NewMockLoginUserUsecase(ctrl *gomock.Controller) *MockLoginUserUsecase {
	mock := &MockLoginUserUsecase{ctrl: ctrl}
	mock.recorder = &MockLoginUserUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoginUserUsecase) EXPECT() *MockLoginUserUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockLoginUserUsecase) Execute(ctx context.Context, in *logmodel.LoginInput) (*logmodel.LoginOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, in)
	ret0, _ := ret[0].(*logmodel.LoginOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockLoginUserUsecaseMockRecorder) Execute(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockLoginUserUsecase)(nil).Execute), ctx, in)
}
