// Code generated by MockGen. DO NOT EDIT.
// Source: ./../../../usecase/interfaces/registration.go
//
// Generated by this command:
//
//	mockgen -source=./../../../usecase/interfaces/registration.go -destination=mocks/mock_registration.go -package=handlmocks
//

// Package handlmocks is a generated GoMock package.
package handlmocks

import (
	context "context"
	reflect "reflect"
	regmodel "userservice/internal/usecase/models/registration"

	gomock "go.uber.org/mock/gomock"
)

// MockRegisterUserUsecase is a mock of RegisterUserUsecase interface.
type MockRegisterUserUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockRegisterUserUsecaseMockRecorder
	isgomock struct{}
}

// MockRegisterUserUsecaseMockRecorder is the mock recorder for MockRegisterUserUsecase.
type MockRegisterUserUsecaseMockRecorder struct {
	mock *MockRegisterUserUsecase
}

// NewMockRegisterUserUsecase creates a new mock instance.
func NewMockRegisterUserUsecase(ctrl *gomock.Controller) *MockRegisterUserUsecase {
	mock := &MockRegisterUserUsecase{ctrl: ctrl}
	mock.recorder = &MockRegisterUserUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegisterUserUsecase) EXPECT() *MockRegisterUserUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockRegisterUserUsecase) Execute(ctx context.Context, in *regmodel.RegInput) (*regmodel.RegOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, in)
	ret0, _ := ret[0].(*regmodel.RegOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockRegisterUserUsecaseMockRecorder) Execute(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockRegisterUserUsecase)(nil).Execute), ctx, in)
}
