// Code generated by MockGen. DO NOT EDIT.
// Source: ./../../../usecase/interfaces/create_task.go
//
// Generated by this command:
//
//	mockgen -source=./../../../usecase/interfaces/create_task.go -destination=./mocks/mock_create_project.go -package=handlmocks
//

// Package handlmocks is a generated GoMock package.
package handlmocks

import (
	context "context"
	reflect "reflect"
	createmodel "taskservice/internal/usecase/models/createtask"

	gomock "go.uber.org/mock/gomock"
)

// MockCreateTaskUsecase is a mock of CreateTaskUsecase interface.
type MockCreateTaskUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockCreateTaskUsecaseMockRecorder
	isgomock struct{}
}

// MockCreateTaskUsecaseMockRecorder is the mock recorder for MockCreateTaskUsecase.
type MockCreateTaskUsecaseMockRecorder struct {
	mock *MockCreateTaskUsecase
}

// NewMockCreateTaskUsecase creates a new mock instance.
func NewMockCreateTaskUsecase(ctrl *gomock.Controller) *MockCreateTaskUsecase {
	mock := &MockCreateTaskUsecase{ctrl: ctrl}
	mock.recorder = &MockCreateTaskUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateTaskUsecase) EXPECT() *MockCreateTaskUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockCreateTaskUsecase) Execute(ctx context.Context, in *createmodel.CreateTaskInput) (*createmodel.CreateTaskOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, in)
	ret0, _ := ret[0].(*createmodel.CreateTaskOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockCreateTaskUsecaseMockRecorder) Execute(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCreateTaskUsecase)(nil).Execute), ctx, in)
}
