// Code generated by MockGen. DO NOT EDIT.
// Source: ./../../../usecase/interfaces/update_task.go
//
// Generated by this command:
//
//	mockgen -source=./../../../usecase/interfaces/update_task.go -destination=./mocks/mock_update_task.go -package=handlmocks
//

// Package handlmocks is a generated GoMock package.
package handlmocks

import (
	context "context"
	reflect "reflect"
	updatemodel "taskservice/internal/usecase/models/updatetask"

	gomock "go.uber.org/mock/gomock"
)

// MockUpdateTaskUsecase is a mock of UpdateTaskUsecase interface.
type MockUpdateTaskUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateTaskUsecaseMockRecorder
	isgomock struct{}
}

// MockUpdateTaskUsecaseMockRecorder is the mock recorder for MockUpdateTaskUsecase.
type MockUpdateTaskUsecaseMockRecorder struct {
	mock *MockUpdateTaskUsecase
}

// NewMockUpdateTaskUsecase creates a new mock instance.
func NewMockUpdateTaskUsecase(ctrl *gomock.Controller) *MockUpdateTaskUsecase {
	mock := &MockUpdateTaskUsecase{ctrl: ctrl}
	mock.recorder = &MockUpdateTaskUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateTaskUsecase) EXPECT() *MockUpdateTaskUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockUpdateTaskUsecase) Execute(ctx context.Context, in *updatemodel.UpdateTaskInput) (*updatemodel.UpdateTaskOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, in)
	ret0, _ := ret[0].(*updatemodel.UpdateTaskOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockUpdateTaskUsecaseMockRecorder) Execute(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockUpdateTaskUsecase)(nil).Execute), ctx, in)
}
