// Code generated by MockGen. DO NOT EDIT.
// Source: ./../../../usecase/interfaces/delete_task.go
//
// Generated by this command:
//
//	mockgen -source=./../../../usecase/interfaces/delete_task.go -destination=./mocks/mock_delete_task.go -package=handlmocks
//

// Package handlmocks is a generated GoMock package.
package handlmocks

import (
	context "context"
	reflect "reflect"
	deletemodel "taskservice/internal/usecase/models/deletetask"

	gomock "go.uber.org/mock/gomock"
)

// MockDeleteTaskUsecase is a mock of DeleteTaskUsecase interface.
type MockDeleteTaskUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteTaskUsecaseMockRecorder
	isgomock struct{}
}

// MockDeleteTaskUsecaseMockRecorder is the mock recorder for MockDeleteTaskUsecase.
type MockDeleteTaskUsecaseMockRecorder struct {
	mock *MockDeleteTaskUsecase
}

// NewMockDeleteTaskUsecase creates a new mock instance.
func NewMockDeleteTaskUsecase(ctrl *gomock.Controller) *MockDeleteTaskUsecase {
	mock := &MockDeleteTaskUsecase{ctrl: ctrl}
	mock.recorder = &MockDeleteTaskUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleteTaskUsecase) EXPECT() *MockDeleteTaskUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockDeleteTaskUsecase) Execute(ctx context.Context, in *deletemodel.DeleteTaskInput) (*deletemodel.DeleteTaskOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, in)
	ret0, _ := ret[0].(*deletemodel.DeleteTaskOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockDeleteTaskUsecaseMockRecorder) Execute(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockDeleteTaskUsecase)(nil).Execute), ctx, in)
}
