// Code generated by MockGen. DO NOT EDIT.
// Source: ./../../../usecase/interfaces/get_all_tasks.go
//
// Generated by this command:
//
//	mockgen -source=./../../../usecase/interfaces/get_all_tasks.go -destination=./mocks/mock_get_all_tasks.go -package=handlmocks
//

// Package handlmocks is a generated GoMock package.
package handlmocks

import (
	context "context"
	reflect "reflect"
	getallmodel "taskservice/internal/usecase/models/getalltasks"

	gomock "go.uber.org/mock/gomock"
)

// MockGetAllTasksUsecase is a mock of GetAllTasksUsecase interface.
type MockGetAllTasksUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockGetAllTasksUsecaseMockRecorder
	isgomock struct{}
}

// MockGetAllTasksUsecaseMockRecorder is the mock recorder for MockGetAllTasksUsecase.
type MockGetAllTasksUsecaseMockRecorder struct {
	mock *MockGetAllTasksUsecase
}

// NewMockGetAllTasksUsecase creates a new mock instance.
func NewMockGetAllTasksUsecase(ctrl *gomock.Controller) *MockGetAllTasksUsecase {
	mock := &MockGetAllTasksUsecase{ctrl: ctrl}
	mock.recorder = &MockGetAllTasksUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetAllTasksUsecase) EXPECT() *MockGetAllTasksUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetAllTasksUsecase) Execute(ctx context.Context, in *getallmodel.GetAllTasksInput) (*getallmodel.GetALlTasksOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, in)
	ret0, _ := ret[0].(*getallmodel.GetALlTasksOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetAllTasksUsecaseMockRecorder) Execute(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetAllTasksUsecase)(nil).Execute), ctx, in)
}
