// Code generated by MockGen. DO NOT EDIT.
// Source: ./../../../usecase/interfaces/get_task.go
//
// Generated by this command:
//
//	mockgen -source=./../../../usecase/interfaces/get_task.go -destination=./mocks/mock_get_task.go -package=handlmocks
//

// Package handlmocks is a generated GoMock package.
package handlmocks

import (
	context "context"
	reflect "reflect"
	getmodel "taskservice/internal/usecase/models/gettask"

	gomock "go.uber.org/mock/gomock"
)

// MockGetTaskUsecase is a mock of GetTaskUsecase interface.
type MockGetTaskUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockGetTaskUsecaseMockRecorder
	isgomock struct{}
}

// MockGetTaskUsecaseMockRecorder is the mock recorder for MockGetTaskUsecase.
type MockGetTaskUsecaseMockRecorder struct {
	mock *MockGetTaskUsecase
}

// NewMockGetTaskUsecase creates a new mock instance.
func NewMockGetTaskUsecase(ctrl *gomock.Controller) *MockGetTaskUsecase {
	mock := &MockGetTaskUsecase{ctrl: ctrl}
	mock.recorder = &MockGetTaskUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetTaskUsecase) EXPECT() *MockGetTaskUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetTaskUsecase) Execute(ctx context.Context, in *getmodel.GetTaskInput) (*getmodel.GetTaskOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, in)
	ret0, _ := ret[0].(*getmodel.GetTaskOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetTaskUsecaseMockRecorder) Execute(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetTaskUsecase)(nil).Execute), ctx, in)
}
