// Code generated by MockGen. DO NOT EDIT.
// Source: ./../../../usecase/interfaces/get_owner_id.go
//
// Generated by this command:
//
//	mockgen -source=./../../../usecase/interfaces/get_owner_id.go -destination=./mocks/mock_getownerid.go -package=grpchandlermocks
//

// Package grpchandlermocks is a generated GoMock package.
package grpchandlermocks

import (
	context "context"
	getowneridmodel "projectservice/internal/usecase/models/getownerid"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGetOwnerIdUsecase is a mock of GetOwnerIdUsecase interface.
type MockGetOwnerIdUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockGetOwnerIdUsecaseMockRecorder
	isgomock struct{}
}

// MockGetOwnerIdUsecaseMockRecorder is the mock recorder for MockGetOwnerIdUsecase.
type MockGetOwnerIdUsecaseMockRecorder struct {
	mock *MockGetOwnerIdUsecase
}

// NewMockGetOwnerIdUsecase creates a new mock instance.
func NewMockGetOwnerIdUsecase(ctrl *gomock.Controller) *MockGetOwnerIdUsecase {
	mock := &MockGetOwnerIdUsecase{ctrl: ctrl}
	mock.recorder = &MockGetOwnerIdUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetOwnerIdUsecase) EXPECT() *MockGetOwnerIdUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetOwnerIdUsecase) Execute(ctx context.Context, in *getowneridmodel.GetOwnerIdInput) (*getowneridmodel.GetOwnerIdOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, in)
	ret0, _ := ret[0].(*getowneridmodel.GetOwnerIdOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetOwnerIdUsecaseMockRecorder) Execute(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetOwnerIdUsecase)(nil).Execute), ctx, in)
}
