// Code generated by MockGen. DO NOT EDIT.
// Source: ./../../../usecase/interfaces/authenticate.go
//
// Generated by this command:
//
//	mockgen -source=./../../../usecase/interfaces/authenticate.go -destination=mocks/mock_authenticate.go -package=grpchandlmocks
//

// Package grpchandlmocks is a generated GoMock package.
package grpchandlmocks

import (
	context "context"
	reflect "reflect"
	authmodel "userservice/internal/usecase/models/authenticate"

	gomock "go.uber.org/mock/gomock"
)

// MockAuthenticateUsecase is a mock of AuthenticateUsecase interface.
type MockAuthenticateUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockAuthenticateUsecaseMockRecorder
	isgomock struct{}
}

// MockAuthenticateUsecaseMockRecorder is the mock recorder for MockAuthenticateUsecase.
type MockAuthenticateUsecaseMockRecorder struct {
	mock *MockAuthenticateUsecase
}

// NewMockAuthenticateUsecase creates a new mock instance.
func NewMockAuthenticateUsecase(ctrl *gomock.Controller) *MockAuthenticateUsecase {
	mock := &MockAuthenticateUsecase{ctrl: ctrl}
	mock.recorder = &MockAuthenticateUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthenticateUsecase) EXPECT() *MockAuthenticateUsecaseMockRecorder {
	return m.recorder
}

// AuthenticateSession mocks base method.
func (m *MockAuthenticateUsecase) AuthenticateSession(ctx context.Context, in *authmodel.AuthInput) (*authmodel.AuthOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthenticateSession", ctx, in)
	ret0, _ := ret[0].(*authmodel.AuthOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthenticateSession indicates an expected call of AuthenticateSession.
func (mr *MockAuthenticateUsecaseMockRecorder) AuthenticateSession(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthenticateSession", reflect.TypeOf((*MockAuthenticateUsecase)(nil).AuthenticateSession), ctx, in)
}
