// Code generated by MockGen. DO NOT EDIT.
// Source: ./../../../usecase/interfaces/authenticate.go
//
// Generated by this command:
//
//	mockgen -source=./../../../usecase/interfaces/authenticate.go -destination=mocks/mock_authenticate.go -package=grpchandlmocks
//

// Package grpchandlmocks is a generated GoMock package.
package grpchandlmocks

import (
	context "context"
	reflect "reflect"
	authmodel "userservice/internal/usecase/models/authenticate"

	gomock "go.uber.org/mock/gomock"
)

// MockGetUserIDBySessionUsecase is a mock of GetUserIDBySessionUsecase interface.
type MockGetUserIDBySessionUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockGetUserIDBySessionUsecaseMockRecorder
	isgomock struct{}
}

// MockGetUserIDBySessionUsecaseMockRecorder is the mock recorder for MockGetUserIDBySessionUsecase.
type MockGetUserIDBySessionUsecaseMockRecorder struct {
	mock *MockGetUserIDBySessionUsecase
}

// NewMockGetUserIDBySessionUsecase creates a new mock instance.
func NewMockGetUserIDBySessionUsecase(ctrl *gomock.Controller) *MockGetUserIDBySessionUsecase {
	mock := &MockGetUserIDBySessionUsecase{ctrl: ctrl}
	mock.recorder = &MockGetUserIDBySessionUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetUserIDBySessionUsecase) EXPECT() *MockGetUserIDBySessionUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetUserIDBySessionUsecase) Execute(ctx context.Context, in *authmodel.AuthInput) (*authmodel.AuthOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, in)
	ret0, _ := ret[0].(*authmodel.AuthOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetUserIDBySessionUsecaseMockRecorder) Execute(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetUserIDBySessionUsecase)(nil).Execute), ctx, in)
}
